use_frameworks!

target 'form-autoheight-cell_Example' do
  pod 'form-autoheight-cell', :path => '../'

  target 'form-autoheight-cell_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
